[package]
name = "ffx"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.24", features = ["derive"] }
thiserror = "1.0.69"
ratatui = "0.27.0"
crossterm = "0.27.0"
shell-words = "1.1.0"
